name: CI/CD - Build, Scan, and GitOps Update

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_URL: ${{ secrets.ECR_URL }}
  GITOPS_REPO: liormilliger/node-js-sample-k8s

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    outputs:
      full_tag: ${{ env.FULL_TAG }} # Pass tag to the next job
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version from package.json
        id: pkg_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "FULL_TAG=${VERSION}-build-${{ github.run_number }}" >> $GITHUB_ENV

      - name: SAST - Code Scan (npm audit)
        run: npm audit --audit-level=high

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_URL }}:${{ env.FULL_TAG }} .
          docker tag ${{ env.ECR_URL }}:${{ env.FULL_TAG }} ${{ env.ECR_URL }}:latest

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ECR_URL }}:${{ env.FULL_TAG }}'
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Image to ECR
        if: github.event_name == 'push'
        run: |
          docker push ${{ env.ECR_URL }}:${{ env.FULL_TAG }}
          docker push ${{ env.ECR_URL }}:latest

  update-gitops:
    needs: build-and-scan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.K8S_REPO_PAT }}
          path: gitops-repo

      - name: Update Image Tag in values.yaml
        run: |
          cd gitops-repo/my-app-chart
          # Use sed to find the line starting with tag: and replace the value
          sed -i "s/tag: .*/tag: \"${{ needs.build-and-scan.outputs.full_tag }}\"/g" values.yaml
          
      - name: Commit and Push Changes
        run: |
          cd gitops-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add my-app-chart/values.yaml
          git commit -m "chore: update image tag to ${{ needs.build-and-scan.outputs.full_tag }} [skip ci]"
          git push origin HEAD